---
resources:
- name: attendee-service-source
  type: git
  source:
    uri: https://github.com/pivotal-enablement/attendee-service
    branch: smoke_tests
- name: deploy-attendee-service
  type: cf
  source:
    api: api.run.pez.pivotal.io
    username: {{cf-user}}
    password: {{cf-password}}
    organization: pivot-twhitney
    space: pal
    skip_cert_check: true

jobs:
- name: test
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
  - task: test
    file: attendee-service-source/ci/tasks/test.yml

- name: deploy
  public: true
  plan:
  - task: package
    file: attendee-service-source/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: attendee-service/manifest.yml
      path: package-output/attendee-service.jar

- name: smoke_test
  public: true
  plan:
  - task: smoke_test
    file: attendee-service-source/ci/tasks/smoke_test.yml
    params:
      ATTENDEE_SERVICE_URL: http://attendee-service-censorable-arrival.cfapps-02.haas-66.pez.pivotal.io
